### ISSUE TITLE
ExifTool is missing

### ISSUE THREAD

**Issue by da2x** [flathub/org.kde.digikam#44]
Hi, the ExifTool component is missing. It has to be bundled into the Flatpak for it to become available to DigiKam. It wasn’t added as part of #39, as far as I can tell.

**Comment by kha84** [comment]
https://forum.kde.org/viewtopic.php?f=255&t=173834

**Comment by kha84** [comment]
I hit the above bug with flatpak version of Digikam neither being able to pick up my exiftool I do have installed nor can't download and install it on its own.

**Comment by kha84** [comment]
Hey @ElXreno thanks for stepping into this. I just updated my Digikam from flatpak but the issue is still the same:
- it doesn't have exiftool preconfigured (or it just cannot find it on its own)
- I cannot point it to use my exiftool I have installed myself to /usr/local/bin (as per https://github.com/platformio/platformio-atom-ide-terminal/issues/664#issuecomment-573045233 that location should be accessible via /var/run/host/usr/local). Symptoms are still the same as above - whenever I point it to that file (Settings -> Configure Digikam -> Metadata -> ExifTool -> Find), nothing happens afterwards, the file selection dialog just getting closed and Digikam still shows as nothing was selected. Tried to restart it but that didn't help. 
Have your above commit was already considered in the last build?

**Comment by kha84** [comment]
Just as a matter of sanity check, I have compiled the same version from sources, and it is able to pick my exiftool up.

**Comment by hfiguiere** [comment]
> Just as a matter of sanity check, I have compiled the same version from sources, and it is able to pick my exiftool up.

but it's not sandboxed. Any attempt to use exiftool that is outside of the flatpak sandbox is doomed to fail.

The solution is for the maintainer of this flatpak to add ExifTool (and Perl).

**Comment by kha84** [comment]
> > Just as a matter of sanity check, I have compiled the same version from sources, and it is able to pick my exiftool up.
> 
> but it's not sandboxed. Any attempt to use exiftool that is outside of the flatpak sandbox is doomed to fail.
> 
> The solution is for the maintainer of this flatpak to add ExifTool (and Perl).

This is something I did just for the sake of testing is that Digikam is not broken itself
